[package]
name = "task-manager-rust-api"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.8.0"
diesel = { version = "2.2.1", features = ["sqlite"] }
dotenvy = "0.15.7"
serde = { version = "1.0", features = ["derive"] }
